### ISSUE TITLE
Possible Bug in Clinical Notes DiagnosticReport and Document Reference Tests

### ISSUE THREAD

**Issue by brianslevin** [onc-healthit/onc-certification-g10-test-kit#131] opened 2022-05-17 20:42 UTC
**Subject of the issue**
Possible Bug in Clinical Notes DiagnosticReport and Document Reference Tests

cannot copy/paste, so see attached screenshot

**Your environment**
* Edition of inferno (Community or Program):
* Version of inferno:
* Which browser and version(s) is the bug present on?:

**Steps to reproduce**
Unsure

Include:

* G10 APIs
* ihsdev4dhapim.ihs.gov
* 4.31.02

**Comment by arscan** [comment] 2022-05-17 21:07
This is definitely a bug because users shouldn't see these kinds of errors.  However, it may be the case that your system is doing something wrong still -- just in a way that our code can't handle.  We're looking at it to see if we can reproduce on our side.

**Comment by yunwwang** [comment] 2022-05-17 23:08
@brianslevin Are you running test on Inferno.health.gov or your locally installed docker image?

**Comment by yunwwang** [comment] 2022-05-18 14:02
I think this is the same as #110 which we have fixed release v2.2.0. @brianslevin Do you test on the latest release?

**Comment by brianslevin** [comment] 2022-05-18 14:24
v 2.2.1 is in the header

**Comment by yunwwang** [comment] 2022-05-18 14:30
That is strange. Do you run on inferno.healthit.gov or your local docker?

**Comment by brianslevin** [comment] 2022-05-18 14:31
on inferno.healthit.gov

**Comment by yunwwang** [comment] 2022-05-18 14:34
Do you have the test session id?

**Comment by brianslevin** [comment] 2022-05-18 14:56
a328f1ef-d1c4-4784-8da9-5d1e5a8425e3

**Comment by yunwwang** [comment] 2022-05-18 15:30
Thanks @brianslevin I see the problem. The session is logged on 2022-05-05 which is before we release v2.2.0 with the fix. Could you run the test again and check if the same error exist?

**Comment by brianslevin** [comment] 2022-05-18 20:21
i will run the test again tomorrow, thank you

**Comment by brianslevin** [comment] 2022-05-19 14:49
I re-ran the test with the same patient and it works now.

thank you

**Comment by yunwwang** [comment] 2022-08-09 15:03
Hello @brianslevin 

I will close this issue as no activities over the last few months. If you experience similar issue in the future, you can reopen this issue or create a new one. 

Thank you

**Closed by yunwwang** 2022-08-09 15:03 UTC
Labels: question answered
