### ISSUE TITLE
Inferno Not Processing Requests or Loading

### ISSUE THREAD

**Issue by dhit-mdavis** [onc-healthit/onc-certification-g10-test-kit#398] opened 2023-02-01 22:30 UTC
Screenshots Below

![image](https://user-images.githubusercontent.com/56314435/216178153-bd2774bd-4320-41ef-a422-ca017daa5efc.png)

![image](https://user-images.githubusercontent.com/56314435/216351845-e3fcf895-a543-467c-acd7-7bfcc82c7eae.png)

**Comment by madhavdarji** [comment] 2023-02-02 12:27
I'm seeing the same issue. No new tests are running. & existing test instances are not loading.

https://inferno.healthit.gov/suites/test_sessions/202265e7-f3a8-49e3-99df-7dcbef74636a#g10_certification-g10_smart_ehr_practitioner_app

**Comment by SavannahDearing** [comment] 2023-02-02 14:28
I've reached out over zulip, I also cannot test, 0/0 and does nothing.

**Comment by dhit-mdavis** [comment] 2023-02-02 14:29
I meant to check Zulip last night as well but only put in this ticket at this point - logging in over there now

**Comment by SavannahDearing** [comment] 2023-02-02 14:35
@yunwwang says they are looking into it :)

**Comment by conkman** [comment] 2023-02-02 14:40
🙏thank you.  What is zulip?  There is no link to support for that coming from inferno.  It took me here. it seems like its working now I am seeing a red banner error now, though. But the tests are running.
![image](https://user-images.githubusercontent.com/5832004/216354525-0e1022c4-0ed9-4e82-82a4-0017f4a31364.png)

**Comment by yunwwang** [comment] 2023-02-02 14:45
The terminology service is still loading the initial code systems. It may take a few minutes.

**Comment by dhit-mdavis** [comment] 2023-02-02 14:46
> 🙏thank you. What is zulip? There is no link to support for that coming from inferno. It took me here. it seems like its working now I am seeing a red banner error now, though. But the tests are running. ![image](https://user-images.githubusercontent.com/5832004/216354525-0e1022c4-0ed9-4e82-82a4-0017f4a31364.png)

Zulip is a forum that you can ask questions and communicate on about all things FHIR

https://chat.fhir.org/#

**Comment by yunwwang** [comment] 2023-02-02 14:47
Here is inferno zulip stream: https://chat.fhir.org/#narrow/stream/179309-inferno

**Comment by yunwwang** [comment] 2023-02-13 16:06
Closed as the issue is resolved after server reboot

**Closed by yunwwang** 2023-02-13 16:06 UTC
