### ISSUE TITLE
SSL Error in Inferno App logs

### ISSUE THREAD

**Issue by godavarthi-seshu** [onc-healthit/onc-certification-g10-test-kit#65] opened 2022-04-01 13:42 UTC
getting SSL error while Inferno is accessing FHIR Endpoint. please share your thoughts ASAP

https://hostname/appname/fhir/metadata

below is the error stack trace.

INFO -- : Initializing client with https://localhost/appname/fhir
[2022-04-01T11:30:35.789578 #1]  INFO -- : Configuring the client to use no authentication.
[2022-04-01T11:30:35.789838 #1]  INFO -- : GETTING: https://localhost/appname/fhir/metadata
[2022-04-01T11:30:35.796039 #1] ERROR -- : SSL Error: https://localhost/appname/fhir/metadata

**Comment by yunwwang** [comment] 2022-04-01 18:30
Hello @godavarthi-seshu 

Thank you for reaching to us. Could you provide more information about the testing environment? 

Is there any details about the SSL error? Thanks

**Comment by godavarthi-seshu** [comment] 2022-04-05 08:02
Hi @yunwwang 

Please refer the attached screenshot for more details about SSL error. it is an Inferno testing environment
<img width="904" alt="SSL Error" src="https://user-images.githubusercontent.com/102810717/161707143-8baa8f74-8502-4dbb-a854-456ca6dbb379.PNG">

**Comment by godavarthi-seshu** [comment] 2022-04-05 14:44
Please tell me if any option to turn off SSL verification certificate in Inferno

**Comment by yunwwang** [comment] 2022-07-12 13:32
I mark this as duplicate of #66

**Closed by yunwwang** 2022-07-12 13:32 UTC
Labels: duplicate
